# Generated by Django 2.2 on 2024-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog', '0002_number_anke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='number',
            name='name',
            field=models.CharField(max_length=1000000),
        ),
    ]
